<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Anggota_ruang extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Anggota_ruang_model');
    } 

    /*
     * Listing of anggota_ruangs
     */
    function index()
    {
        $data['anggota_ruangs'] = $this->Anggota_ruang_model->get_all_anggota_ruangs();
        
        $data['_view'] = 'anggota_ruang/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new anggota_ruang
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('IDENTIFIER_ANGGOTA','IDENTIFIER ANGGOTA','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ID_USER' => $this->input->post('ID_USER'),
				'ID_RUANG' => $this->input->post('ID_RUANG'),
				'IDENTIFIER_ANGGOTA' => $this->input->post('IDENTIFIER_ANGGOTA'),
            );
            
            $anggota_ruang_id = $this->Anggota_ruang_model->add_anggota_ruang($params);
            redirect('anggota_ruang/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();

			$this->load->model('Ruang_model');
			$data['all_ruangs'] = $this->Ruang_model->get_all_ruangs();
            
            $data['_view'] = 'anggota_ruang/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a anggota_ruang
     */
    function edit($ID_ANGGOTA_RUANG)
    {   
        // check if the anggota_ruang exists before trying to edit it
        $data['anggota_ruang'] = $this->Anggota_ruang_model->get_anggota_ruang($ID_ANGGOTA_RUANG);
        
        if(isset($data['anggota_ruang']['ID_ANGGOTA_RUANG']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('IDENTIFIER_ANGGOTA','IDENTIFIER ANGGOTA','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'ID_USER' => $this->input->post('ID_USER'),
					'ID_RUANG' => $this->input->post('ID_RUANG'),
					'IDENTIFIER_ANGGOTA' => $this->input->post('IDENTIFIER_ANGGOTA'),
                );

                $this->Anggota_ruang_model->update_anggota_ruang($ID_ANGGOTA_RUANG,$params);            
                redirect('anggota_ruang/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

				$this->load->model('Ruang_model');
				$data['all_ruangs'] = $this->Ruang_model->get_all_ruangs();

                $data['_view'] = 'anggota_ruang/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The anggota_ruang you are trying to edit does not exist.');
    } 

    /*
     * Deleting anggota_ruang
     */
    function remove($ID_ANGGOTA_RUANG)
    {
        $anggota_ruang = $this->Anggota_ruang_model->get_anggota_ruang($ID_ANGGOTA_RUANG);

        // check if the anggota_ruang exists before trying to delete it
        if(isset($anggota_ruang['ID_ANGGOTA_RUANG']))
        {
            $this->Anggota_ruang_model->delete_anggota_ruang($ID_ANGGOTA_RUANG);
            redirect('anggota_ruang/index');
        }
        else
            show_error('The anggota_ruang you are trying to delete does not exist.');
    }
    
}
