<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_kartu_bingo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_kartu_bingo_model');
    } 

    /*
     * Listing of detail_kartu_bingos
     */
    function index()
    {
        $data['detail_kartu_bingos'] = $this->Detail_kartu_bingo_model->get_all_detail_kartu_bingos();
        
        $data['_view'] = 'detail_kartu_bingo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detail_kartu_bingo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ID_SOAL_PELAJARAN' => $this->input->post('ID_SOAL_PELAJARAN'),
				'ID_KARTU_BINGO' => $this->input->post('ID_KARTU_BINGO'),
            );
            
            $detail_kartu_bingo_id = $this->Detail_kartu_bingo_model->add_detail_kartu_bingo($params);
            redirect('detail_kartu_bingo/index');
        }
        else
        {
			$this->load->model('Soal_pelajaran_model');
			$data['all_soal_pelajarans'] = $this->Soal_pelajaran_model->get_all_soal_pelajarans();

			$this->load->model('Artu_bingo_model');
			$data['all_kartu_bingos'] = $this->Artu_bingo_model->get_all_kartu_bingos();
            
            $data['_view'] = 'detail_kartu_bingo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detail_kartu_bingo
     */
    function edit($ID_DETAIL_KARTU_BINGO)
    {   
        // check if the detail_kartu_bingo exists before trying to edit it
        $data['detail_kartu_bingo'] = $this->Detail_kartu_bingo_model->get_detail_kartu_bingo($ID_DETAIL_KARTU_BINGO);
        
        if(isset($data['detail_kartu_bingo']['ID_DETAIL_KARTU_BINGO']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ID_SOAL_PELAJARAN' => $this->input->post('ID_SOAL_PELAJARAN'),
					'ID_KARTU_BINGO' => $this->input->post('ID_KARTU_BINGO'),
                );

                $this->Detail_kartu_bingo_model->update_detail_kartu_bingo($ID_DETAIL_KARTU_BINGO,$params);            
                redirect('detail_kartu_bingo/index');
            }
            else
            {
				$this->load->model('Soal_pelajaran_model');
				$data['all_soal_pelajarans'] = $this->Soal_pelajaran_model->get_all_soal_pelajarans();

				$this->load->model('Artu_bingo_model');
				$data['all_kartu_bingos'] = $this->Artu_bingo_model->get_all_kartu_bingos();

                $data['_view'] = 'detail_kartu_bingo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detail_kartu_bingo you are trying to edit does not exist.');
    } 

    /*
     * Deleting detail_kartu_bingo
     */
    function remove($ID_DETAIL_KARTU_BINGO)
    {
        $detail_kartu_bingo = $this->Detail_kartu_bingo_model->get_detail_kartu_bingo($ID_DETAIL_KARTU_BINGO);

        // check if the detail_kartu_bingo exists before trying to delete it
        if(isset($detail_kartu_bingo['ID_DETAIL_KARTU_BINGO']))
        {
            $this->Detail_kartu_bingo_model->delete_detail_kartu_bingo($ID_DETAIL_KARTU_BINGO);
            redirect('detail_kartu_bingo/index');
        }
        else
            show_error('The detail_kartu_bingo you are trying to delete does not exist.');
    }
    
}
