<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_menu_model');
    } 

    /*
     * Listing of detail_menus
     */
    function index()
    {
        $data['detail_menus'] = $this->Detail_menu_model->get_all_detail_menus();
        
        $data['_view'] = 'detail_menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detail_menu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ID_PARENT' => $this->input->post('ID_PARENT'),
				'TEKS_MENU' => $this->input->post('TEKS_MENU'),
				'ICONS' => $this->input->post('ICONS'),
				'LINK' => $this->input->post('LINK'),
            );
            
            $detail_menu_id = $this->Detail_menu_model->add_detail_menu($params);
            redirect('detail_menu/index');
        }
        else
        {			$data['all_detail_menus'] = $this->Detail_menu_model->get_all_detail_menus();
            
            $data['_view'] = 'detail_menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detail_menu
     */
    function edit($ID_DETAIL_MENU)
    {   
        // check if the detail_menu exists before trying to edit it
        $data['detail_menu'] = $this->Detail_menu_model->get_detail_menu($ID_DETAIL_MENU);
        
        if(isset($data['detail_menu']['ID_DETAIL_MENU']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ID_PARENT' => $this->input->post('ID_PARENT'),
					'TEKS_MENU' => $this->input->post('TEKS_MENU'),
					'ICONS' => $this->input->post('ICONS'),
					'LINK' => $this->input->post('LINK'),
                );

                $this->Detail_menu_model->update_detail_menu($ID_DETAIL_MENU,$params);            
                redirect('detail_menu/index');
            }
            else
            {				$data['all_detail_menus'] = $this->Detail_menu_model->get_all_detail_menus();

                $data['_view'] = 'detail_menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detail_menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting detail_menu
     */
    function remove($ID_DETAIL_MENU)
    {
        $detail_menu = $this->Detail_menu_model->get_detail_menu($ID_DETAIL_MENU);

        // check if the detail_menu exists before trying to delete it
        if(isset($detail_menu['ID_DETAIL_MENU']))
        {
            $this->Detail_menu_model->delete_detail_menu($ID_DETAIL_MENU);
            redirect('detail_menu/index');
        }
        else
            show_error('The detail_menu you are trying to delete does not exist.');
    }
    
}
