<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Instansi_pendidikan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Instansi_pendidikan_model');
    } 

    /*
     * Listing of instansi_pendidikans
     */
    function index()
    {
        $data['instansi_pendidikans'] = $this->Instansi_pendidikan_model->get_all_instansi_pendidikans();
        
        $data['_view'] = 'instansi_pendidikan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new instansi_pendidikan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('NAMA_INSTANSI_PENDIDIKAN','NAMA INSTANSI PENDIDIKAN','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ID_STATUS_INSTANSI' => $this->input->post('ID_STATUS_INSTANSI'),
				'NAMA_INSTANSI_PENDIDIKAN' => $this->input->post('NAMA_INSTANSI_PENDIDIKAN'),
				'ALAMAT_INSTANSI_PENDIDIKAN' => $this->input->post('ALAMAT_INSTANSI_PENDIDIKAN'),
            );
            
            $instansi_pendidikan_id = $this->Instansi_pendidikan_model->add_instansi_pendidikan($params);
            redirect('instansi_pendidikan/index');
        }
        else
        {
			$this->load->model('Status_instansi_model');
			$data['all_status_instansis'] = $this->Status_instansi_model->get_all_status_instansis();
            
            $data['_view'] = 'instansi_pendidikan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a instansi_pendidikan
     */
    function edit($ID_INSTANSI_PENDIDIKAN)
    {   
        // check if the instansi_pendidikan exists before trying to edit it
        $data['instansi_pendidikan'] = $this->Instansi_pendidikan_model->get_instansi_pendidikan($ID_INSTANSI_PENDIDIKAN);
        
        if(isset($data['instansi_pendidikan']['ID_INSTANSI_PENDIDIKAN']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('NAMA_INSTANSI_PENDIDIKAN','NAMA INSTANSI PENDIDIKAN','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'ID_STATUS_INSTANSI' => $this->input->post('ID_STATUS_INSTANSI'),
					'NAMA_INSTANSI_PENDIDIKAN' => $this->input->post('NAMA_INSTANSI_PENDIDIKAN'),
					'ALAMAT_INSTANSI_PENDIDIKAN' => $this->input->post('ALAMAT_INSTANSI_PENDIDIKAN'),
                );

                $this->Instansi_pendidikan_model->update_instansi_pendidikan($ID_INSTANSI_PENDIDIKAN,$params);            
                redirect('instansi_pendidikan/index');
            }
            else
            {
				$this->load->model('Status_instansi_model');
				$data['all_status_instansis'] = $this->Status_instansi_model->get_all_status_instansis();

                $data['_view'] = 'instansi_pendidikan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The instansi_pendidikan you are trying to edit does not exist.');
    } 

    /*
     * Deleting instansi_pendidikan
     */
    function remove($ID_INSTANSI_PENDIDIKAN)
    {
        $instansi_pendidikan = $this->Instansi_pendidikan_model->get_instansi_pendidikan($ID_INSTANSI_PENDIDIKAN);

        // check if the instansi_pendidikan exists before trying to delete it
        if(isset($instansi_pendidikan['ID_INSTANSI_PENDIDIKAN']))
        {
            $this->Instansi_pendidikan_model->delete_instansi_pendidikan($ID_INSTANSI_PENDIDIKAN);
            redirect('instansi_pendidikan/index');
        }
        else
            show_error('The instansi_pendidikan you are trying to delete does not exist.');
    }
    
}
