<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kartu_bingo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Artu_bingo_model');
    } 

    /*
     * Listing of kartu_bingos
     */
    function index()
    {
        $data['kartu_bingos'] = $this->Artu_bingo_model->get_all_kartu_bingos();
        
        $data['_view'] = 'kartu_bingo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kartu_bingo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TGL_DIBUAT' => $this->input->post('TGL_DIBUAT'),
            );
            
            $kartu_bingo_id = $this->Artu_bingo_model->add_kartu_bingo($params);
            redirect('kartu_bingo/index');
        }
        else
        {            
            $data['_view'] = 'kartu_bingo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kartu_bingo
     */
    function edit($ID_KARTU_BINGO)
    {   
        // check if the kartu_bingo exists before trying to edit it
        $data['kartu_bingo'] = $this->Artu_bingo_model->get_kartu_bingo($ID_KARTU_BINGO);
        
        if(isset($data['kartu_bingo']['ID_KARTU_BINGO']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TGL_DIBUAT' => $this->input->post('TGL_DIBUAT'),
                );

                $this->Artu_bingo_model->update_kartu_bingo($ID_KARTU_BINGO,$params);            
                redirect('kartu_bingo/index');
            }
            else
            {
                $data['_view'] = 'kartu_bingo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kartu_bingo you are trying to edit does not exist.');
    } 

    /*
     * Deleting kartu_bingo
     */
    function remove($ID_KARTU_BINGO)
    {
        $kartu_bingo = $this->Artu_bingo_model->get_kartu_bingo($ID_KARTU_BINGO);

        // check if the kartu_bingo exists before trying to delete it
        if(isset($kartu_bingo['ID_KARTU_BINGO']))
        {
            $this->Artu_bingo_model->delete_kartu_bingo($ID_KARTU_BINGO);
            redirect('kartu_bingo/index');
        }
        else
            show_error('The kartu_bingo you are trying to delete does not exist.');
    }
    
}
