<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Login_model');
    } 

    /*
     * Listing of logins
     */
    function index()
    {
        $data['logins'] = $this->Login_model->get_all_logins();
        
        $data['_view'] = 'login/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new login
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'USERNAME_LOGIN' => $this->input->post('USERNAME_LOGIN'),
				'PASSWORD_LOGIN' => $this->input->post('PASSWORD_LOGIN'),
				'LAST_LOGIN' => $this->input->post('LAST_LOGIN'),
            );
            
            $login_id = $this->Login_model->add_login($params);
            redirect('login/index');
        }
        else
        {            
            $data['_view'] = 'login/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a login
     */
    function edit($ID_TBL_LOGIN)
    {   
        // check if the login exists before trying to edit it
        $data['login'] = $this->Login_model->get_login($ID_TBL_LOGIN);
        
        if(isset($data['login']['ID_TBL_LOGIN']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'USERNAME_LOGIN' => $this->input->post('USERNAME_LOGIN'),
					'PASSWORD_LOGIN' => $this->input->post('PASSWORD_LOGIN'),
					'LAST_LOGIN' => $this->input->post('LAST_LOGIN'),
                );

                $this->Login_model->update_login($ID_TBL_LOGIN,$params);            
                redirect('login/index');
            }
            else
            {
                $data['_view'] = 'login/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The login you are trying to edit does not exist.');
    } 

    /*
     * Deleting login
     */
    function remove($ID_TBL_LOGIN)
    {
        $login = $this->Login_model->get_login($ID_TBL_LOGIN);

        // check if the login exists before trying to delete it
        if(isset($login['ID_TBL_LOGIN']))
        {
            $this->Login_model->delete_login($ID_TBL_LOGIN);
            redirect('login/index');
        }
        else
            show_error('The login you are trying to delete does not exist.');
    }
    
}
