<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ruang extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ruang_model');
    } 

    /*
     * Listing of ruangs
     */
    function index()
    {
        $data['ruangs'] = $this->Ruang_model->get_all_ruangs();
        
        $data['_view'] = 'ruang/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ruang
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ID_INSTANSI_PENDIDIKAN' => $this->input->post('ID_INSTANSI_PENDIDIKAN'),
				'NAMA_RUANG' => $this->input->post('NAMA_RUANG'),
				'KETERANGAN_RUANG' => $this->input->post('KETERANGAN_RUANG'),
            );
            
            $ruang_id = $this->Ruang_model->add_ruang($params);
            redirect('ruang/index');
        }
        else
        {
			$this->load->model('Instansi_pendidikan_model');
			$data['all_instansi_pendidikans'] = $this->Instansi_pendidikan_model->get_all_instansi_pendidikans();
            
            $data['_view'] = 'ruang/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ruang
     */
    function edit($ID_RUANG)
    {   
        // check if the ruang exists before trying to edit it
        $data['ruang'] = $this->Ruang_model->get_ruang($ID_RUANG);
        
        if(isset($data['ruang']['ID_RUANG']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ID_INSTANSI_PENDIDIKAN' => $this->input->post('ID_INSTANSI_PENDIDIKAN'),
					'NAMA_RUANG' => $this->input->post('NAMA_RUANG'),
					'KETERANGAN_RUANG' => $this->input->post('KETERANGAN_RUANG'),
                );

                $this->Ruang_model->update_ruang($ID_RUANG,$params);            
                redirect('ruang/index');
            }
            else
            {
				$this->load->model('Instansi_pendidikan_model');
				$data['all_instansi_pendidikans'] = $this->Instansi_pendidikan_model->get_all_instansi_pendidikans();

                $data['_view'] = 'ruang/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The ruang you are trying to edit does not exist.');
    } 

    /*
     * Deleting ruang
     */
    function remove($ID_RUANG)
    {
        $ruang = $this->Ruang_model->get_ruang($ID_RUANG);

        // check if the ruang exists before trying to delete it
        if(isset($ruang['ID_RUANG']))
        {
            $this->Ruang_model->delete_ruang($ID_RUANG);
            redirect('ruang/index');
        }
        else
            show_error('The ruang you are trying to delete does not exist.');
    }
    
}
