<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Soal_pelajaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Soal_pelajaran_model');
    } 

    /*
     * Listing of soal_pelajarans
     */
    function index()
    {
        $data['soal_pelajarans'] = $this->Soal_pelajaran_model->get_all_soal_pelajarans_join();
        
        $data['_view'] = 'soal_pelajaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new soal_pelajaran
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ID_PELAJARAN' => $this->input->post('ID_PELAJARAN'),
				'TEKS_SOAL_PELAJARAN' => $this->input->post('TEKS_SOAL_PELAJARAN'),
            );
            
            $soal_pelajaran_id = $this->Soal_pelajaran_model->add_soal_pelajaran($params);
            redirect('soal_pelajaran/index');
        }
        else
        {
            $data['_spesific_script'] = 'layouts/_editors';

			$this->load->model('Pelajaran_model');
			$data['all_pelajarans'] = $this->Pelajaran_model->get_all_pelajarans();
            
            $data['_view'] = 'soal_pelajaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a soal_pelajaran
     */
    function edit($ID_SOAL_PELAJARAN)
    {   
        $data['_spesific_script'] = 'layouts/_editors';

        // check if the soal_pelajaran exists before trying to edit it
        $data['soal_pelajaran'] = $this->Soal_pelajaran_model->get_soal_pelajaran($ID_SOAL_PELAJARAN);
        
        if(isset($data['soal_pelajaran']['ID_SOAL_PELAJARAN']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ID_PELAJARAN' => $this->input->post('ID_PELAJARAN'),
					'TEKS_SOAL_PELAJARAN' => $this->input->post('TEKS_SOAL_PELAJARAN'),
                );

                $this->Soal_pelajaran_model->update_soal_pelajaran($ID_SOAL_PELAJARAN,$params);            
                redirect('soal_pelajaran/index');
            }
            else
            {
				$this->load->model('Pelajaran_model');
				$data['all_pelajarans'] = $this->Pelajaran_model->get_all_pelajarans();

                $data['_view'] = 'soal_pelajaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The soal_pelajaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting soal_pelajaran
     */
    function remove($ID_SOAL_PELAJARAN)
    {
        $soal_pelajaran = $this->Soal_pelajaran_model->get_soal_pelajaran($ID_SOAL_PELAJARAN);

        // check if the soal_pelajaran exists before trying to delete it
        if(isset($soal_pelajaran['ID_SOAL_PELAJARAN']))
        {
            $this->Soal_pelajaran_model->delete_soal_pelajaran($ID_SOAL_PELAJARAN);
            redirect('soal_pelajaran/index');
        }
        else
            show_error('The soal_pelajaran you are trying to delete does not exist.');
    }
    
}
