<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_instansi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_instansi_model');
    } 

    /*
     * Listing of status_instansis
     */
    function index()
    {
        $data['status_instansis'] = $this->Status_instansi_model->get_all_status_instansis();
        
        $data['_view'] = 'status_instansi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new status_instansi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TEKS_STATUS_INSTANSI' => $this->input->post('TEKS_STATUS_INSTANSI'),
				'KETERANGAN_STATUS_INSTANSI' => $this->input->post('KETERANGAN_STATUS_INSTANSI'),
            );
            
            $status_instansi_id = $this->Status_instansi_model->add_status_instansi($params);
            redirect('status_instansi/index');
        }
        else
        {            
            $data['_view'] = 'status_instansi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a status_instansi
     */
    function edit($ID_STATUS_INSTANSI)
    {   
        // check if the status_instansi exists before trying to edit it
        $data['status_instansi'] = $this->Status_instansi_model->get_status_instansi($ID_STATUS_INSTANSI);
        
        if(isset($data['status_instansi']['ID_STATUS_INSTANSI']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TEKS_STATUS_INSTANSI' => $this->input->post('TEKS_STATUS_INSTANSI'),
					'KETERANGAN_STATUS_INSTANSI' => $this->input->post('KETERANGAN_STATUS_INSTANSI'),
                );

                $this->Status_instansi_model->update_status_instansi($ID_STATUS_INSTANSI,$params);            
                redirect('status_instansi/index');
            }
            else
            {
                $data['_view'] = 'status_instansi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The status_instansi you are trying to edit does not exist.');
    } 

    /*
     * Deleting status_instansi
     */
    function remove($ID_STATUS_INSTANSI)
    {
        $status_instansi = $this->Status_instansi_model->get_status_instansi($ID_STATUS_INSTANSI);

        // check if the status_instansi exists before trying to delete it
        if(isset($status_instansi['ID_STATUS_INSTANSI']))
        {
            $this->Status_instansi_model->delete_status_instansi($ID_STATUS_INSTANSI);
            redirect('status_instansi/index');
        }
        else
            show_error('The status_instansi you are trying to delete does not exist.');
    }
    
}
