<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_user extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_user_model');
    } 

    /*
     * Listing of status_users
     */
    function index()
    {
        $data['status_users'] = $this->Status_user_model->get_all_status_users();
        
        $data['_view'] = 'status_user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new status_user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'TEKS_STATUS_USER' => $this->input->post('TEKS_STATUS_USER'),
				'KETRANGAN__STATUS_USER' => $this->input->post('KETRANGAN__STATUS_USER'),
            );
            
            $status_user_id = $this->Status_user_model->add_status_user($params);
            redirect('status_user/index');
        }
        else
        {            
            $data['_view'] = 'status_user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a status_user
     */
    function edit($ID_STATUS_USER)
    {   
        // check if the status_user exists before trying to edit it
        $data['status_user'] = $this->Status_user_model->get_status_user($ID_STATUS_USER);
        
        if(isset($data['status_user']['ID_STATUS_USER']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'TEKS_STATUS_USER' => $this->input->post('TEKS_STATUS_USER'),
					'KETRANGAN__STATUS_USER' => $this->input->post('KETRANGAN__STATUS_USER'),
                );

                $this->Status_user_model->update_status_user($ID_STATUS_USER,$params);            
                redirect('status_user/index');
            }
            else
            {
                $data['_view'] = 'status_user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The status_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting status_user
     */
    function remove($ID_STATUS_USER)
    {
        $status_user = $this->Status_user_model->get_status_user($ID_STATUS_USER);

        // check if the status_user exists before trying to delete it
        if(isset($status_user['ID_STATUS_USER']))
        {
            $this->Status_user_model->delete_status_user($ID_STATUS_USER);
            redirect('status_user/index');
        }
        else
            show_error('The status_user you are trying to delete does not exist.');
    }
    
}
