<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_detail_model');
    } 

    /*
     * Listing of user_details
     */
    function index()
    {
        $data['user_details'] = $this->User_detail_model->get_all_user_details();
        
        $data['_view'] = 'user_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_detail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'NAMA_USER' => $this->input->post('NAMA_USER'),
				'ALAMAT_USER' => $this->input->post('ALAMAT_USER'),
				'JK_USER' => $this->input->post('JK_USER'),
				'TELP_USER' => $this->input->post('TELP_USER'),
				'EMAIL_USER' => $this->input->post('EMAIL_USER'),
            );
            
            $user_detail_id = $this->User_detail_model->add_user_detail($params);
            redirect('user_detail/index');
        }
        else
        {            
            $data['_view'] = 'user_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_detail
     */
    function edit($ID_USER_DETAILS)
    {   
        // check if the user_detail exists before trying to edit it
        $data['user_detail'] = $this->User_detail_model->get_user_detail($ID_USER_DETAILS);
        
        if(isset($data['user_detail']['ID_USER_DETAILS']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'NAMA_USER' => $this->input->post('NAMA_USER'),
					'ALAMAT_USER' => $this->input->post('ALAMAT_USER'),
					'JK_USER' => $this->input->post('JK_USER'),
					'TELP_USER' => $this->input->post('TELP_USER'),
					'EMAIL_USER' => $this->input->post('EMAIL_USER'),
                );

                $this->User_detail_model->update_user_detail($ID_USER_DETAILS,$params);            
                redirect('user_detail/index');
            }
            else
            {
                $data['_view'] = 'user_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_detail
     */
    function remove($ID_USER_DETAILS)
    {
        $user_detail = $this->User_detail_model->get_user_detail($ID_USER_DETAILS);

        // check if the user_detail exists before trying to delete it
        if(isset($user_detail['ID_USER_DETAILS']))
        {
            $this->User_detail_model->delete_user_detail($ID_USER_DETAILS);
            redirect('user_detail/index');
        }
        else
            show_error('The user_detail you are trying to delete does not exist.');
    }
    
}
