<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Anggota_ruang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get anggota_ruang by ID_ANGGOTA_RUANG
     */
    function get_anggota_ruang($ID_ANGGOTA_RUANG)
    {
        return $this->db->get_where('TBL_ANGGOTA_RUANG',array('ID_ANGGOTA_RUANG'=>$ID_ANGGOTA_RUANG))->row_array();
    }
        
    /*
     * Get all anggota_ruangs
     */
    function get_all_anggota_ruangs()
    {
        $this->db->order_by('ID_ANGGOTA_RUANG', 'desc');
        return $this->db->get('TBL_ANGGOTA_RUANG')->result_array();
    }
        
    /*
     * function to add new anggota_ruang
     */
    function add_anggota_ruang($params)
    {
        $this->db->insert('TBL_ANGGOTA_RUANG',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update anggota_ruang
     */
    function update_anggota_ruang($ID_ANGGOTA_RUANG,$params)
    {
        $this->db->where('ID_ANGGOTA_RUANG',$ID_ANGGOTA_RUANG);
        return $this->db->update('TBL_ANGGOTA_RUANG',$params);
    }
    
    /*
     * function to delete anggota_ruang
     */
    function delete_anggota_ruang($ID_ANGGOTA_RUANG)
    {
        return $this->db->delete('TBL_ANGGOTA_RUANG',array('ID_ANGGOTA_RUANG'=>$ID_ANGGOTA_RUANG));
    }
}
