<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail_menu by ID_DETAIL_MENU
     */
    function get_detail_menu($ID_DETAIL_MENU)
    {
        return $this->db->get_where('TBL_DETAIL_MENU',array('ID_DETAIL_MENU'=>$ID_DETAIL_MENU))->row_array();
    }
        
    /*
     * Get all detail_menus
     */
    function get_all_detail_menus()
    {
        $this->db->order_by('ID_DETAIL_MENU', 'desc');
        return $this->db->get('TBL_DETAIL_MENU')->result_array();
    }
        
    /*
     * function to add new detail_menu
     */
    function add_detail_menu($params)
    {
        $this->db->insert('TBL_DETAIL_MENU',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail_menu
     */
    function update_detail_menu($ID_DETAIL_MENU,$params)
    {
        $this->db->where('ID_DETAIL_MENU',$ID_DETAIL_MENU);
        return $this->db->update('TBL_DETAIL_MENU',$params);
    }
    
    /*
     * function to delete detail_menu
     */
    function delete_detail_menu($ID_DETAIL_MENU)
    {
        return $this->db->delete('TBL_DETAIL_MENU',array('ID_DETAIL_MENU'=>$ID_DETAIL_MENU));
    }
}
