<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Instansi_pendidikan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get instansi_pendidikan by ID_INSTANSI_PENDIDIKAN
     */
    function get_instansi_pendidikan($ID_INSTANSI_PENDIDIKAN)
    {
        return $this->db->get_where('TBL_INSTANSI_PENDIDIKAN',array('ID_INSTANSI_PENDIDIKAN'=>$ID_INSTANSI_PENDIDIKAN))->row_array();
    }
        
    /*
     * Get all instansi_pendidikans
     */
    function get_all_instansi_pendidikans()
    {
        $this->db->order_by('ID_INSTANSI_PENDIDIKAN', 'desc');
        return $this->db->get('TBL_INSTANSI_PENDIDIKAN')->result_array();
    }
        
    /*
     * function to add new instansi_pendidikan
     */
    function add_instansi_pendidikan($params)
    {
        $this->db->insert('TBL_INSTANSI_PENDIDIKAN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update instansi_pendidikan
     */
    function update_instansi_pendidikan($ID_INSTANSI_PENDIDIKAN,$params)
    {
        $this->db->where('ID_INSTANSI_PENDIDIKAN',$ID_INSTANSI_PENDIDIKAN);
        return $this->db->update('TBL_INSTANSI_PENDIDIKAN',$params);
    }
    
    /*
     * function to delete instansi_pendidikan
     */
    function delete_instansi_pendidikan($ID_INSTANSI_PENDIDIKAN)
    {
        return $this->db->delete('TBL_INSTANSI_PENDIDIKAN',array('ID_INSTANSI_PENDIDIKAN'=>$ID_INSTANSI_PENDIDIKAN));
    }
}
