<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jawaban_soal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jawaban_soal by ID_JAWABAN_SOAL
     */
    function get_jawaban_soal($ID_JAWABAN_SOAL)
    {
        return $this->db->get_where('TBL_JAWABAN_SOAL',array('ID_JAWABAN_SOAL'=>$ID_JAWABAN_SOAL))->row_array();
    }
        
    /*
     * Get all jawaban_soals
     */
    function get_all_jawaban_soals()
    {
        $this->db->order_by('ID_JAWABAN_SOAL', 'desc');
        return $this->db->get('TBL_JAWABAN_SOAL')->result_array();
    }
        
    /*
     * function to add new jawaban_soal
     */
    function add_jawaban_soal($params)
    {
        $this->db->insert('TBL_JAWABAN_SOAL',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jawaban_soal
     */
    function update_jawaban_soal($ID_JAWABAN_SOAL,$params)
    {
        $this->db->where('ID_JAWABAN_SOAL',$ID_JAWABAN_SOAL);
        return $this->db->update('TBL_JAWABAN_SOAL',$params);
    }
    
    /*
     * function to delete jawaban_soal
     */
    function delete_jawaban_soal($ID_JAWABAN_SOAL)
    {
        return $this->db->delete('TBL_JAWABAN_SOAL',array('ID_JAWABAN_SOAL'=>$ID_JAWABAN_SOAL));
    }

    /*
     * function to show jawaban based on soal
     */
    function get_jawaban_soal_by_soal($ID_SOAL_PELAJARAN)
    {
        $this->db->select('*');
        $this->db->from('TBL_JAWABAN_SOAL');
        $this->db->join('TBL_SOAL_PELAJARAN', 'TBL_SOAL_PELAJARAN.ID_SOAL_PELAJARAN = TBL_JAWABAN_SOAL.ID_SOAL_PELAJARAN', 'left');
        $this->db->where('TBL_JAWABAN_SOAL.ID_SOAL_PELAJARAN', $ID_SOAL_PELAJARAN);
        return $this->db->get()->result_array();
    }

    function get_soal($ID_SOAL_PELAJARAN){
        $this->db->select('*');
        $this->db->from('TBL_SOAL_PELAJARAN');
        $this->db->where('ID_SOAL_PELAJARAN', $ID_SOAL_PELAJARAN);
        return $this->db->get()->result_array();
    }
}
