<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get login by ID_TBL_LOGIN
     */
    function get_login($ID_TBL_LOGIN)
    {
        return $this->db->get_where('TBL_LOGIN',array('ID_TBL_LOGIN'=>$ID_TBL_LOGIN))->row_array();
    }
        
    /*
     * Get all logins
     */
    function get_all_logins()
    {
        $this->db->order_by('ID_TBL_LOGIN', 'desc');
        return $this->db->get('TBL_LOGIN')->result_array();
    }
        
    /*
     * function to add new login
     */
    function add_login($params)
    {
        $this->db->insert('TBL_LOGIN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update login
     */
    function update_login($ID_TBL_LOGIN,$params)
    {
        $this->db->where('ID_TBL_LOGIN',$ID_TBL_LOGIN);
        return $this->db->update('TBL_LOGIN',$params);
    }
    
    /*
     * function to delete login
     */
    function delete_login($ID_TBL_LOGIN)
    {
        return $this->db->delete('TBL_LOGIN',array('ID_TBL_LOGIN'=>$ID_TBL_LOGIN));
    }

    function check_user($table,$where)
    {
        return $this->db->get_where($table,$where);
    }

    function get_user_data_by_id_login($id_tbl_login){
        $this->db->select('*');
        $this->db->from('tbl_user');
        $this->db->join('tbl_user_details', 'tbl_user_details.ID_USER_DETAILS = tbl_user.ID_USER_DETAILS', 'left');

        $this->db->join('tbl_status_user', 'tbl_status_user.ID_STATUS_USER = tbl_user.ID_STATUS_USER', 'left');
        
        $this->db->where('ID_TBL_LOGIN', $id_tbl_login);
        $query = $this->db->get(); 
        if($query->num_rows() != 0)
        {
            return $query->row_array();
        }
        else
        {
            return false;
        }
    }

    // return JSON data

    function get_logins_json($data)
    {
        $this->db->select('*');
        $this->db->from('tbl_login');
        $this->db->where('USERNAME_LOGIN', $data); 
        $query = $this->db->get();
        return $query->result();
    }
}
