<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get login by ID_TBL_LOGIN
     */
    function get_login($ID_TBL_LOGIN)
    {
        return $this->db->get_where('TBL_LOGIN',array('ID_TBL_LOGIN'=>$ID_TBL_LOGIN))->row_array();
    }
        
    /*
     * Get all logins
     */
    function get_all_logins()
    {
        $this->db->order_by('ID_TBL_LOGIN', 'desc');
        return $this->db->get('TBL_LOGIN')->result_array();
    }
        
    /*
     * function to add new login
     */
    function add_login($params)
    {
        $this->db->insert('TBL_LOGIN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update login
     */
    function update_login($ID_TBL_LOGIN,$params)
    {
        $this->db->where('ID_TBL_LOGIN',$ID_TBL_LOGIN);
        return $this->db->update('TBL_LOGIN',$params);
    }
    
    /*
     * function to delete login
     */
    function delete_login($ID_TBL_LOGIN)
    {
        return $this->db->delete('TBL_LOGIN',array('ID_TBL_LOGIN'=>$ID_TBL_LOGIN));
    }
}
