<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu by ID_MENU
     */
    function get_menu($ID_MENU)
    {
        return $this->db->get_where('TBL_MENU',array('ID_MENU'=>$ID_MENU))->row_array();
    }
        
    /*
     * Get all menus
     */
    function get_all_menus()
    {
        $this->db->order_by('ID_MENU', 'desc');
        return $this->db->get('TBL_MENU')->result_array();
    }
        
    /*
     * function to add new menu
     */
    function add_menu($params)
    {
        $this->db->insert('TBL_MENU',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu
     */
    function update_menu($ID_MENU,$params)
    {
        $this->db->where('ID_MENU',$ID_MENU);
        return $this->db->update('TBL_MENU',$params);
    }
    
    /*
     * function to delete menu
     */
    function delete_menu($ID_MENU)
    {
        return $this->db->delete('TBL_MENU',array('ID_MENU'=>$ID_MENU));
    }
}
