<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pelajaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pelajaran by ID_PELAJARAN
     */
    function get_pelajaran($ID_PELAJARAN)
    {
        return $this->db->get_where('TBL_PELAJARAN',array('ID_PELAJARAN'=>$ID_PELAJARAN))->row_array();
    }

      /*
     * Get pelajaran by ID_RUANG
     */
    function get_pelajaran_by_ruang($ID_RUANG)
    {
        return $this->db->get_where('TBL_PELAJARAN',array('ID_RUANG'=>$ID_RUANG))->result_array();
    }

        
    /*
     * Get all pelajarans
     */
    function get_all_pelajarans()
    {
        $this->db->order_by('ID_PELAJARAN', 'desc');
        return $this->db->get('TBL_PELAJARAN')->result_array();
    }
        
    /*
     * function to add new pelajaran
     */
    function add_pelajaran($params)
    {
        $this->db->insert('TBL_PELAJARAN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pelajaran
     */
    function update_pelajaran($ID_PELAJARAN,$params)
    {
        $this->db->where('ID_PELAJARAN',$ID_PELAJARAN);
        return $this->db->update('TBL_PELAJARAN',$params);
    }
    
    /*
     * function to delete pelajaran
     */
    function delete_pelajaran($ID_PELAJARAN)
    {
        return $this->db->delete('TBL_PELAJARAN',array('ID_PELAJARAN'=>$ID_PELAJARAN));
    }

    /*
     * Get all pelajarans Join
     */
    function get_all_pelajarans_join()
    {

        $this->db->select('*');
        $this->db->from('tbl_pelajaran');
        $this->db->join('tbl_ruang', 'tbl_ruang.ID_RUANG = tbl_pelajaran.ID_RUANG', 'left');
        return $this->db->get()->result_array();
    }
}
