<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ruang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ruang by ID_RUANG
     */
    function get_ruang($ID_RUANG)
    {
        return $this->db->get_where('TBL_RUANG',array('ID_RUANG'=>$ID_RUANG))->row_array();
    }
        
    /*
     * Get all ruangs
     */
    function get_all_ruangs()
    {
        $this->db->order_by('ID_RUANG', 'desc');
        return $this->db->get('TBL_RUANG')->result_array();
    }
        
    /*
     * function to add new ruang
     */
    function add_ruang($params)
    {
        $this->db->insert('TBL_RUANG',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ruang
     */
    function update_ruang($ID_RUANG,$params)
    {
        $this->db->where('ID_RUANG',$ID_RUANG);
        return $this->db->update('TBL_RUANG',$params);
    }
    
    /*
     * function to delete ruang
     */
    function delete_ruang($ID_RUANG)
    {
        return $this->db->delete('TBL_RUANG',array('ID_RUANG'=>$ID_RUANG));
    }
}
