<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Soal_pelajaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get soal_pelajaran by ID_SOAL_PELAJARAN
     */
    function get_soal_pelajaran($ID_SOAL_PELAJARAN)
    {
        return $this->db->get_where('TBL_SOAL_PELAJARAN',array('ID_SOAL_PELAJARAN'=>$ID_SOAL_PELAJARAN))->row_array();
    }
        
    /*
     * Get all soal_pelajarans
     */
    function get_all_soal_pelajarans()
    {
        $this->db->order_by('ID_SOAL_PELAJARAN', 'desc');
        return $this->db->get('TBL_SOAL_PELAJARAN')->result_array();
    }
        
    /*
     * function to add new soal_pelajaran
     */
    function add_soal_pelajaran($params)
    {
        $this->db->insert('TBL_SOAL_PELAJARAN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update soal_pelajaran
     */
    function update_soal_pelajaran($ID_SOAL_PELAJARAN,$params)
    {
        $this->db->where('ID_SOAL_PELAJARAN',$ID_SOAL_PELAJARAN);
        return $this->db->update('TBL_SOAL_PELAJARAN',$params);
    }
    
    /*
     * function to delete soal_pelajaran
     */
    function delete_soal_pelajaran($ID_SOAL_PELAJARAN)
    {
        return $this->db->delete('TBL_SOAL_PELAJARAN',array('ID_SOAL_PELAJARAN'=>$ID_SOAL_PELAJARAN));
    }

    /*
     * Get all soal_pelajarans Join
     */
    function get_all_soal_pelajarans_join()
    {
        $this->db->select('*');
        $this->db->from('tbl_soal_pelajaran');
        $this->db->join('tbl_pelajaran', 'tbl_pelajaran.ID_PELAJARAN = tbl_soal_pelajaran.ID_PELAJARAN', 'left');
        return $this->db->get()->result_array();
    }
}
