<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get status_user by ID_STATUS_USER
     */
    function get_status_user($ID_STATUS_USER)
    {
        return $this->db->get_where('TBL_STATUS_USER',array('ID_STATUS_USER'=>$ID_STATUS_USER))->row_array();
    }
        
    /*
     * Get all status_users
     */
    function get_all_status_users()
    {
        $this->db->order_by('ID_STATUS_USER', 'desc');
        return $this->db->get('TBL_STATUS_USER')->result_array();
    }
        
    /*
     * function to add new status_user
     */
    function add_status_user($params)
    {
        $this->db->insert('TBL_STATUS_USER',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update status_user
     */
    function update_status_user($ID_STATUS_USER,$params)
    {
        $this->db->where('ID_STATUS_USER',$ID_STATUS_USER);
        return $this->db->update('TBL_STATUS_USER',$params);
    }
    
    /*
     * function to delete status_user
     */
    function delete_status_user($ID_STATUS_USER)
    {
        return $this->db->delete('TBL_STATUS_USER',array('ID_STATUS_USER'=>$ID_STATUS_USER));
    }
}
