<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_instansi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get status_instansi by ID_STATUS_INSTANSI
     */
    function get_status_instansi($ID_STATUS_INSTANSI)
    {
        return $this->db->get_where('TBL_STATUS_INSTANSI',array('ID_STATUS_INSTANSI'=>$ID_STATUS_INSTANSI))->row_array();
    }
        
    /*
     * Get all status_instansis
     */
    function get_all_status_instansis()
    {
        $this->db->order_by('ID_STATUS_INSTANSI', 'desc');
        return $this->db->get('TBL_STATUS_INSTANSI')->result_array();
    }
        
    /*
     * function to add new status_instansi
     */
    function add_status_instansi($params)
    {
        $this->db->insert('TBL_STATUS_INSTANSI',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update status_instansi
     */
    function update_status_instansi($ID_STATUS_INSTANSI,$params)
    {
        $this->db->where('ID_STATUS_INSTANSI',$ID_STATUS_INSTANSI);
        return $this->db->update('TBL_STATUS_INSTANSI',$params);
    }
    
    /*
     * function to delete status_instansi
     */
    function delete_status_instansi($ID_STATUS_INSTANSI)
    {
        return $this->db->delete('TBL_STATUS_INSTANSI',array('ID_STATUS_INSTANSI'=>$ID_STATUS_INSTANSI));
    }
}
