<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_detail by ID_USER_DETAILS
     */
    function get_user_detail($ID_USER_DETAILS)
    {
        return $this->db->get_where('TBL_USER_DETAILS',array('ID_USER_DETAILS'=>$ID_USER_DETAILS))->row_array();
    }
        
    /*
     * Get all user_details
     */
    function get_all_user_details()
    {
        $this->db->order_by('ID_USER_DETAILS', 'desc');
        return $this->db->get('TBL_USER_DETAILS')->result_array();
    }
        
    /*
     * function to add new user_detail
     */
    function add_user_detail($params)
    {
        $this->db->insert('TBL_USER_DETAILS',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_detail
     */
    function update_user_detail($ID_USER_DETAILS,$params)
    {
        $this->db->where('ID_USER_DETAILS',$ID_USER_DETAILS);
        return $this->db->update('TBL_USER_DETAILS',$params);
    }
    
    /*
     * function to delete user_detail
     */
    function delete_user_detail($ID_USER_DETAILS)
    {
        return $this->db->delete('TBL_USER_DETAILS',array('ID_USER_DETAILS'=>$ID_USER_DETAILS));
    }
}
